apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec: 
  acme: 
    server: https://acme-v02.api.letsencrypt.org/directory
    email: fabiolnh@gmail.com
    privateKeySecretRef:
      name: letsencrypt-tls