apiVersion: v1
kind: Secret
metadata:
  name: goserver-secret
type: Opaque
data:
  USER: "RmFiaW8K" # It has to be in Base64 ( command to generate: 'echo "Fabio" | base64 ) (OBS: In kubernetes, as we can see, use secret is not so secure, and there is not way to be more secure. The only difference is that is not so clear for who is seeing it.)
  PASSWORD: "MTIzNAo=" # It has to be in Base64 ( command to generate: 'echo "1234" | base64 ) (OBS: In kubernetes, as we can see, use secret is not so secure, and there is not way to be more secure. The only difference is that is not so clear for who is seeing it.)